### ISSUE TITLE
How dose differ from NetworkImage? 

### ISSUE THREAD

**Issue by omzer** [axross/firebase_storage_image#6]
Looks to me like both do the same job, I'm I right?

**Comment by lukepighetti** [comment]
Yeah, it does appear to do the exact same thing, and it also does not appear to cache the image.

**Comment by aryzhov** [comment]
@omzer @lukepighetti There are two ways to retrieve a file from Firebase Storage: via `gs://` and via `https://`. The former works universally for all files and uses firebase authentication, the latter requires a token. Unless you know the token, which is different for every file and can be changed, you won't be able to use `NetworkImage` to retrieve the image from Firebase Storage.
