### ISSUE TITLE
The package doesn't compile with Flutter SDK >= 1.6.0

### ISSUE THREAD

**Issue by aryzhov** [axross/firebase_storage_image#8]
I get the following error after upgrading Flutter to 1.6.5:

```
Compiler message:
file:///Users/alex/code/firebase_storage_image/lib/firebase_storage_image.dart:58:31: Error: The argument type 'Null Function(dynamic)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/alex/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (information) {
                              ^
```
I looked into the issue and found that in Flutter 1.6.0 the signature of `InformationCollector` has changed. I have a fix and will submit a pull request shortly.

**Comment by aryzhov** [comment]
@axross You can get notifications about pull requests and new issues by clicking the Watch button at the top of the page. It's important to react to issues timely. Please take a look at my pull request. Thank you!

**Comment by axross** [comment]
I just merged your pull request! Thank you!
